### ISSUE TITLE
outreachy applicant

### ISSUE THREAD

**Issue by Nigale-Djomo** [zarr-developers/tutorials#2]
Hello

Hope you are doing good on this day.
My name is Nigale and i am an outreachy applicant.
Can this task be assigned to me, i will like to work on.

Best

**Comment by joshmoore** [comment]
Thanks for reaching out, @Nigale-Djomo. Let's keep all the general chat communication on gitter at https://gitter.im/zarr-developers/outreachy-contributors-dec-2022. Welcome to Zarr & Outreachy!
