### ISSUE TITLE
Outreachy Applicant

### ISSUE THREAD

**Issue by victorvictoria-maker** [zarr-developers/tutorials#4]
@joshmoore @MSanKeys963 
I am interested in contributing to Zarr's tutorial project. I would be glad if a task is assigned to me.
Victoria Victor, Outreachy applicant.

**Comment by joshmoore** [comment]
Thanks for reaching out, @victorvictoria-maker. Let's keep all the general chat communication on gitter at https://gitter.im/zarr-developers/outreachy-contributors-dec-2022. Welcome to Zarr & Outreachy!
